pipeline {
  agent any
  stages {	
	stage('Maven Compile'){
		steps{
			echo 'Project compile stage'
			bat label: 'Compilation running', script: '''mvn -f credit-union-project/pom.xml compile'''
	       	}
	}
	
	stage('Unit Test') {
	   steps {
			echo 'Project Testing stage'
			bat label: 'Test running', script: '''mvn -f credit-union-project/pom.xml test'''
	       
       		}
   	}

	stage('Jacoco Coverage Report') {
        	steps{
            		jacoco()
		}
	}
       
       stage('SonarQube'){
		steps{
				bat label: '', script: '''mvn -f credit-union-project/pom.xml sonar:sonar \
				-Dsonar.host.url=http://localhost:9000 \
				-Dsonar.login=70f65acd1bca791bb882bbc943f3fc1eeff7a31d'''
			}
   		}
	
	stage('Maven Package'){
		steps{
			echo 'Project packaging stage'
			bat label: 'Project packaging', script: '''mvn -f credit-union-project/pom.xml package'''
		}
	} 		
    
  }
}

